"""
navigator_engine.py — PenteIA V4.0
Exports simulation results as MITRE ATT&CK Navigator v4.x layer JSON.
"""
import json
from typing import Optional

NAVIGATOR_VERSION = "4.9"
ATT_CK_VERSION = "14"
LAYER_FORMAT = "4.5"


# Colour mapping by simulation outcome
COLORS = {
    "found":        "#ff6666",   # red — technique succeeded (gap)
    "blocked":      "#00ff00",   # green — blocked
    "partial":      "#ffcc00",   # yellow — partial detection
    "not_tested":   "#cccccc",   # grey — not in scope
}

SCORE_MAP = {
    "found": 100,
    "blocked": 0,
    "partial": 50,
    "not_tested": 0,
}


def build_navigator_layer(simulation: dict, layer_name: Optional[str] = None) -> dict:
    """
    Build a MITRE ATT&CK Navigator layer from a PenteIA simulation result.

    simulation: dict with keys:
      - target: str
      - score: float
      - date: str
      - techniques: list of {id, name, tactic, status, severity}
    """
    techniques = simulation.get("techniques", [])
    name = layer_name or f"PenteIA — {simulation.get('target', 'Unknown')} — {simulation.get('date', '')[:10]}"

    technique_entries = []
    for t in techniques:
        tid = t.get("id", "")
        status = t.get("status", "not_tested")

        # Skip non-standard MITRE IDs (e.g. BR-* Brazilian techniques)
        if not tid.startswith("T"):
            continue

        # Sub-technique support: T1059.001 → technique T1059, sub .001
        if "." in tid:
            parts = tid.split(".")
            attack_id = parts[0]
            sub_id = ".".join(parts)
        else:
            attack_id = tid
            sub_id = None

        entry = {
            "techniqueID": sub_id or attack_id,
            "tactic": _tactic_to_navigator(t.get("tactic", "")),
            "color": COLORS.get(status, COLORS["not_tested"]),
            "comment": f"PenteIA: {t.get('name', '')} — {status}",
            "enabled": True,
            "metadata": [
                {"name": "status", "value": status},
                {"name": "severity", "value": t.get("severity", "")},
                {"name": "source", "value": "PenteIA V4.0"},
            ],
            "links": [],
            "showSubtechniques": False,
        }

        if sub_id:
            entry["isSubtechnique"] = True

        # Add score for heatmap view
        entry["score"] = SCORE_MAP.get(status, 0)

        technique_entries.append(entry)

    layer = {
        "name": name,
        "versions": {
            "attack": ATT_CK_VERSION,
            "navigator": NAVIGATOR_VERSION,
            "layer": LAYER_FORMAT,
        },
        "domain": "enterprise-attack",
        "description": (
            f"Generated by PenteIA V4.0 | Target: {simulation.get('target', '?')} | "
            f"Risk Score: {simulation.get('score', 0):.1f}% | "
            f"Techniques tested: {len(techniques)}"
        ),
        "filters": {"platforms": ["Windows", "Linux", "macOS"]},
        "sorting": 0,
        "layout": {
            "layout": "side",
            "aggregateFunction": "max",
            "showID": True,
            "showName": True,
            "showAggregateScores": True,
            "countUnscored": False,
        },
        "hideDisabled": False,
        "techniques": technique_entries,
        "gradient": {
            "colors": ["#ff6666", "#ffcc00", "#00ff00"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Técnica encontrada (gap)", "color": COLORS["found"]},
            {"label": "Bloqueada/Detectada",      "color": COLORS["blocked"]},
            {"label": "Detecção parcial",          "color": COLORS["partial"]},
            {"label": "Não testada",               "color": COLORS["not_tested"]},
        ],
        "metadata": [
            {"name": "generated_by", "value": "PenteIA V4.0"},
            {"name": "target", "value": simulation.get("target", "")},
            {"name": "score", "value": str(simulation.get("score", 0))},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#1a1a2e",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
        "selectVisibleTechniques": False,
    }

    return layer


def export_layer_json(simulation: dict, layer_name: Optional[str] = None) -> str:
    """Return the Navigator layer as a JSON string."""
    layer = build_navigator_layer(simulation, layer_name)
    return json.dumps(layer, ensure_ascii=False, indent=2)


def _tactic_to_navigator(tactic: str) -> str:
    """Convert PenteIA tactic name to ATT&CK Navigator tactic ID."""
    mapping = {
        "RECONNAISSANCE": "reconnaissance",
        "RESOURCE_DEVELOPMENT": "resource-development",
        "INITIAL_ACCESS": "initial-access",
        "EXECUTION": "execution",
        "PERSISTENCE": "persistence",
        "PRIVILEGE_ESCALATION": "privilege-escalation",
        "DEFENSE_EVASION": "defense-evasion",
        "CREDENTIAL_ACCESS": "credential-access",
        "DISCOVERY": "discovery",
        "LATERAL_MOVEMENT": "lateral-movement",
        "COLLECTION": "collection",
        "COMMAND_AND_CONTROL": "command-and-control",
        "EXFILTRATION": "exfiltration",
        "IMPACT": "impact",
    }
    return mapping.get(tactic.upper(), tactic.lower().replace("_", "-"))
